### ISSUE TITLE
TCAdmin.SDK.Security.SecurityException: 'Access is denied.'

### ISSUE THREAD

**Issue by connorjjarvis** [Alexr03/TCAdmin-Wrapper#1]
I've been trying to get your wrapper to work, I've set up everything as per the readme and I have now reached a point where I'm trying to run the restart server bit and I'm getting this response when executing this code:
`Service service = new Service(1)`
Results in: TCAdmin.SDK.Security.SecurityException: 'Access is denied.'

I seem to be able to do other methods like, GetServices() which does return all the services, is there something else I've missed during the setup?

**Comment by Alexr03** [comment]
Hello,

Are you able to restart the service manually on the panel?

Cheers.
Alex

**Comment by Alexr03** [comment]
Any update? @connorjjarvis

**Comment by Alexr03** [comment]
Closing.
